- hosts: localhost
  vars:
    - local_user: "{{ lookup('env', 'USER') }}"
    - git_username: "minkminkk"
    - git_user_email: "mrminhlunvn1@gmail.com"
    - src_ssh_key: "./.ssh/id_ed25519_personal"
    - dest_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_personal"
    - python_version: "3.11"
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        update_cache: yes
  tasks:
    - name: SET UP CORE PACKAGES
      include_tasks: tasks/core.yml
      tags: core
    - name: SET UP SSH
      include_tasks: tasks/ssh.yml
      tags:
        - ssh
        - git-personal  # requires ssh
    - name: SET UP GIT
      include_tasks: tasks/git.yml
      tags: git-personal
    - name: SET UP PYTHON
      include_tasks: tasks/python.yml
      tags: python
    - name: SET UP IBUS (VN typing)
      include_tasks: tasks/ibus.yml
      tags: ibus
    - name: SET UP ZSH
      include_tasks: tasks/zsh.yml
      tags: zsh