- hosts: localhost
  vars:
    - local_user: "{{ lookup('env', 'USER') }}"
    - src_ssh_key: "./.ssh/id_ed25519_personal"
    - dest_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519_personal"
  pre_tasks:
    - name: Add apt repos
      include_tasks: pre-tasks/apt-ppa-repos.yml
  tasks:
    - name: SET UP SSH
      include_tasks: tasks/ssh.yml
    - name: SET UP CORE PACKAGES
      include_tasks: tasks/core.yml
    - name: CONFIGURE GIT
      include_tasks: tasks/git.yml
    - name: SET UP IBUS (VN typing)
      include_tasks: tasks/ibus.yml
    - name: SET UP ZSH
      include_tasks: tasks/zsh.yml