- name: Add Python apt repository
  become: true
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: Install Python
  become: true
  apt:
    name: "python{{ python_version }}"
  
- name: Install Python venv
  become: true
  apt:
    name: "python{{ python_version }}-venv"