- name: Add ibus apt repository
  become: true
  apt_repository:
    repo: ppa:bamboo-engine/ibus-bamboo
    state: present
  tags: ibus

- name: Install ibus
  become: true
  apt:
    name:
      - ibus
      - ibus-bamboo
    install_recommends: true
  tags: ibus

- name: Configure Bamboo engine
  shell: |
    dconf write /desktop/ibus/general/preload-engines "['BambooUs', 'Bamboo']"
    dconf write /org/gnome/desktop/input-sources "['BambooUs', 'Bamboo']"