- name: Add ibus apt repository
  become: true
  apt_repository:
    repo: ppa:bamboo-engine/ibus-bamboo
    state: present
  tags: ibus

- name: Install ibus
  become: true
  apt:
    name:
      - ibus
      - ibus-bamboo
    install_recommends: true
  tags: ibus

- name: Configure Bamboo engine
  dconf:
    key: "/desktop/ibus/general/preload-engines"
    value: "['BambooUs', 'Bamboo']"
    state: present

- name: Configure keyboard input sources
  dconf:
    key: "/org/gnome/desktop/input-sources"
    value: "['BambooUs', 'Bamboo']"
    state: present