- name: Install zsh
  become: true
  apt:
    name: zsh
  tags: zsh
    
- name: Change shell to zsh
  become: true
  shell: chsh -s $(which zsh) {{ local_user }}
  tags: zsh

- name: Check that the somefile.conf exists
  stat:
    path: "/home/{{ local_user }}/.oh-my-zsh"
  register: oh_my_stats
  tags: zsh

- name: Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_stats.stat.exists == False
  become_user: "{{ local_user }}"
  tags: zsh

# - name: Install zsh-autosuggestions
#   ansible.builtin.git:
#     repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
#     dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
#   tags: zsh

# - name: Install zsh-autocomplete
#   ansible.builtin.git:
#     repo: "https://github.com/marlonrichert/zsh-autocomplete.git"
#     dest: "~/.oh-my-zsh/plugins/zsh-autocomplete"
#     depth: 1
#   tags: zsh